### PR TITLE
Update composer.json to work with Laravel 5.1

### PR DESCRIPTION
**Pull request by marklj**

### CODE REVIEW

**Comment by atrauzzi** [comment]
Would you be able to change it so that it works with 5 or 5.1?  Probably aren't any issues in supporting both...

**Comment by josenicomaia** [comment]
I am using Laravel 5.1 and Doctrine too. I had 2 problems.
- #96 
- In \Atrauzzi\LaravelDoctrine\ServiceProvider::register i had to change:
from:
```php
                        $this->app->singleton('\Doctrine\ORM\EntityManager', function (Application $app) {
                            return EntityManager::create(
                                $this->getDoctrineConnection(),
                                $this->createDoctrineConfig($this->createCache()),
                                $this->createEventManager()
                            );
```
to:
```php
                       $this->app->singleton('\Doctrine\ORM\EntityManager', function (Application $app) {
                            $em = EntityManager::create(
                                $this->getDoctrineConnection(),
                                $this->createDoctrineConfig($this->createCache()),
                                $this->createEventManager()
                            );

                            $platform = $em->getConnection()->getDatabasePlatform();
                            $platform->registerDoctrineTypeMapping('enum', 'string');
                            
                            return $em;
			});
```

**Comment by marklj** [comment]
I usually just add that code to add enum support within my application's service provider.

**Comment by josenicomaia** [comment]
Great!

I changed to:
```php
public function boot() {
            $platform = $this->app->make('doctrine.connection')->getDatabasePlatform();
            $platform->registerDoctrineTypeMapping('enum', 'string');

            ...
}
```

**Pull request merged**
