### PR TITLE
adding doctrine driver authenticator

### PR DESCRIPTION
**Pull request by manfredjb**
* This change allows developers use `doctrine.auth` as auth driver.
* DoctrineAuthenticator class is in charge of validate user credentials according to the user model
* readme.md file was updated with all the specifications

### CODE REVIEW

**Comment by atrauzzi** [comment]
Would I be able to get you to use tabs instead of spaces?

**Comment by manfredjb** [comment]
actually I do not use spaces. However, I see a strange format in the ServiceProvider boot function. Let me fix it.

**Comment by atrauzzi** [comment]
Ah, apologies, github expands them.  I keep forgetting that.  Okay, you've tested to make sure these changes don't break anything?

**Comment by manfredjb** [comment]
I have tested it, It works well. Hope people take a minute at least to read the readme file. But everything is debugged and tested.

**Pull request merged**
