### PR TITLE
Less restrictive doctrine version

### PR DESCRIPTION
**Pull request by RayRutjes**
Doctrine 2.5 has actually some nice features that I use like Embeddable annotations. Don't think there are huge BC issues.

### CODE REVIEW

**Comment by RayRutjes** [comment]
I have also corrected the console command bindings, by injected the dependencies.

**Comment by atrauzzi** [comment]
Any chance you could convert all those spaces to tabs?

**Comment by RayRutjes** [comment]
Let me know if it suits you.

**Comment by atrauzzi** [comment]
Well, you just hit the whole project with an auto-format :P

**Comment by RayRutjes** [comment]
I guess I'll try to find some time to do this.

**Pull request closed without merging**
