### PR TITLE
XML and YAML Configuration

### PR DESCRIPTION
**Pull request by joshjwalker**
# YAML and XML Configuration 

I've gone ahead and added in YAML and XML to the ServiceProvider by implementing YAMLDriver and XMLDriver into the switch statement for determining the driver. To use, just update the 'driver' key to YAML or XML respectively. In addition, define your 'paths' key to where ever your mapping files are located. 

# DoctrineExtensions

I've also added in DoctrineExtensions which allow you to use trig functions in SQL such as COS, ACOS (etc). If this is not desirable, I can remove this extension from the code. 

Any feedback or things that I've executed properly, please let me know and I will take care of them.

### CODE REVIEW

**Comment by afibanez** [comment]
Cool! I need yaml too :smile:

**Comment by atrauzzi** [comment]
Can you update with tabs instead of spaces?

**Comment by joshjwalker** [comment]
For sure. I will get that done in the next couple of days.

**Comment by joshjwalker** [comment]
Updated

**Pull request merged**
